import { createClient } from '@/lib/supabase/server'
import { PageHeader } from '@/components/app-shell'
import { Card, CardBody, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'

export const dynamic = 'force-dynamic'

export default async function NotificationsPage() {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const { data: notifs = [] } = await supabase
    .from('notifications').select('*').eq('user_id', user!.id).order('created_at', { ascending: false }).limit(50)

  return (
    <>
      <PageHeader title="Alerts" subtitle="Email and push events generated by your portfolio." />
      <div className="p-6">
        <Card>
          <CardHeader><CardTitle>Recent</CardTitle><CardDescription>Last 50 events.</CardDescription></CardHeader>
          <CardBody className="p-0">
            {(notifs ?? []).length === 0 ? (
              <p className="px-6 py-6 text-sm text-ink-500">No alerts yet.</p>
            ) : (
              <ul className="divide-y hairline divide-ink-100">
                {(notifs as any[]).map((n) => (
                  <li key={n.id} className="px-6 py-3">
                    <div className="flex items-center justify-between">
                      <p className="text-sm font-medium text-ink-900">{n.subject}</p>
                      <span className="text-xs text-ink-500">{new Date(n.created_at).toLocaleString('en-GB')}</span>
                    </div>
                    <p className="mt-1 text-sm text-ink-600">{n.body}</p>
                  </li>
                ))}
              </ul>
            )}
          </CardBody>
        </Card>
      </div>
    </>
  )
}
